In [44]:
import pandas
import numpy as np
from sklearn import linear_model
import pathlib 


file_path = pathlib.Path("C:\\Users\\15165\\OneDrive - stevens.edu\\AIRS\\Combined data folder\\Training Data.xlsx")
df = pandas.read_excel(file_path)
df

Families_with_children  Public HS Graduates  Unemployment Rate  \
0                      12707               186250                4.6   
1                      12716               186250                4.6   
2                      12722               186250                4.6   
3                      12710               186250                4.6   
4                      12684               186250                4.6   
...                      ...                  ...                ...   
1589                   10324               178810                7.8   
1590                   10291               178810                7.8   
1591                   10266               178810                7.8   
1592                   10274               178810                7.8   
1593                   10261               178810                7.8   

      Max Temp  Precipitation  
0           21           0.00  
1           23           0.05  
2           22           0.00  
3           18           0.00  
4           24           0.00  
...        ...            ...  
1589        83           0.00  
1590        80           0.00  
1591        82           0.00  
1592        78           0.25  
1593        90           0.00  

[1594 rows x 5 columns]

In [38]:
#reg = linear_model.LinearRegression()
#reg.fit(df[['Date of Census','Unemployment Rate','Max Temp','Precipitation','Public HS Graduates']],df.Families_with_children)

y= df.iloc[:,:1].values
x=df.iloc[:,1:].values
x


array([[1.8625e+05, 4.6000e+00, 2.1000e+01, 0.0000e+00],
       [1.8625e+05, 4.6000e+00, 2.3000e+01, 5.0000e-02],
       [1.8625e+05, 4.6000e+00, 2.2000e+01, 0.0000e+00],
       ...,
       [1.7881e+05, 7.8000e+00, 8.2000e+01, 0.0000e+00],
       [1.7881e+05, 7.8000e+00, 7.8000e+01, 2.5000e-01],
       [1.7881e+05, 7.8000e+00, 9.0000e+01, 0.0000e+00]])

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [40]:
x_train

array([[1.8155e+05, 5.4000e+00, 8.5000e+01, 0.0000e+00],
       [1.8155e+05, 5.6000e+00, 2.5000e+01, 0.0000e+00],
       [1.8262e+05, 4.9000e+00, 8.5000e+01, 0.0000e+00],
       ...,
       [1.7911e+05, 6.0000e+00, 9.2000e+01, 0.0000e+00],
       [1.8262e+05, 4.9000e+00, 8.4000e+01, 0.0000e+00],
       [1.8262e+05, 4.8000e+00, 5.4000e+01, 1.0100e+00]])

In [41]:
from sklearn.linear_model import LinearRegression

In [43]:
regressor = LinearRegression()

In [46]:
regressor.fit(x_train,y_train)

LinearRegression()

In [47]:
pred=regressor.predict(x_test)
pred

array([[12089.38380941],
       [10795.70326171],
       [12592.13270442],
       [11287.7283424 ],
       [11680.44211575],
       [12432.51672943],
       [12386.78828051],
       [11081.94419931],
       [11543.17505391],
       [11215.29391118],
       [12232.15375561],
       [10902.78432344],
       [11925.44323805],
       [11963.66278111],
       [12373.2463389 ],
       [12058.86907516],
       [11978.88208561],
       [11116.27327534],
       [12394.41696407],
       [12852.46487392],
       [12768.38724946],
       [11176.93594708],
       [10581.08599182],
       [12589.31335361],
       [11020.88012554],
       [12482.08640308],
       [10998.00632076],
       [11040.02450233],
       [12783.80672185],
       [11215.29391118],
       [12669.37646841],
       [12745.65212436],
       [10302.75322963],
       [12009.32069462],
       [10561.98633372],
       [12327.47423752],
       [11031.59647209],
       [11222.92259474],
       [12741.85348586],
       [11703.33934611],


In [51]:
print(y_test)

[[11597]
 [10543]
 [12382]
 [11277]
 [12349]
 [12158]
 [11963]
 [10796]
 [11742]
 [11266]
 [12957]
 [10772]
 [11697]
 [12045]
 [12382]
 [11606]
 [11728]
 [10736]
 [11999]
 [12821]
 [12501]
 [11065]
 [10551]
 [12387]
 [10738]
 [12166]
 [10831]
 [10754]
 [12864]
 [11266]
 [12435]
 [12832]
 [10483]
 [11689]
 [10610]
 [12304]
 [10760]
 [11288]
 [13012]
 [12105]
 [12264]
 [12112]
 [12257]
 [11728]
 [10774]
 [11814]
 [12876]
 [12400]
 [11067]
 [11415]
 [12857]
 [12785]
 [12013]
 [10554]
 [12842]
 [12264]
 [11861]
 [10788]
 [12936]
 [12737]
 [12174]
 [12168]
 [12005]
 [12124]
 [12742]
 [10613]
 [11982]
 [10804]
 [12909]
 [11496]
 [10311]
 [12822]
 [10568]
 [12837]
 [12459]
 [10794]
 [12028]
 [12167]
 [12765]
 [12144]
 [12711]
 [12358]
 [11823]
 [10555]
 [12927]
 [12185]
 [12454]
 [12912]
 [10573]
 [11686]
 [11967]
 [12172]
 [12388]
 [13195]
 [12545]
 [10632]
 [12992]
 [12597]
 [10562]
 [12530]
 [11963]
 [11776]
 [12098]
 [11521]
 [11586]
 [12626]
 [11579]
 [12456]
 [10546]
 [12685]
 [12452]
 

In [1]:
import matplotlib.pyplot