In [4]:
import pandas
import numpy as np
from sklearn import linear_model
import pathlib 

#C:\\Users\\15165\\OneDrive - stevens.edu\\AIRS\\Combined data folder\\Training Data.xlsx

file_path = pathlib.Path("Combined Data.xlsx")
df = pandas.read_excel(file_path)
df

Families with Children in Shelter  Public HS Graduates  \
0                                  9514               182720   
1                                  9508               182720   
2                                  9571               182720   
3                                  9624               182720   
4                                  9612               182720   
...                                 ...                  ...   
2754                              10324               178810   
2755                              10291               178810   
2756                              10266               178810   
2757                              10274               178810   
2758                              10261               178810   

      Unemployment Rate  Max Temp  Precipitation  
0                   8.4        54           0.00  
1                   8.4        64           0.00  
2                   8.4        43           0.00  
3                   8.4        41           0.00  
4                   8.4        34           0.00  
...                 ...       ...            ...  
2754                7.8        83           0.00  
2755                7.8        80           0.00  
2756                7.8        82           0.00  
2757                7.8        78           0.25  
2758                7.8        90           0.00  

[2759 rows x 5 columns]

In [5]:
#reg = linear_model.LinearRegression()
#reg.fit(df[['Date of Census','Unemployment Rate','Max Temp','Precipitation','Public HS Graduates']],df.Families_with_children)

y= df.iloc[:,:1].values
x=df.iloc[:,1:].values
x


array([[1.8272e+05, 8.4000e+00, 5.4000e+01, 0.0000e+00],
       [1.8272e+05, 8.4000e+00, 6.4000e+01, 0.0000e+00],
       [1.8272e+05, 8.4000e+00, 4.3000e+01, 0.0000e+00],
       ...,
       [1.7881e+05, 7.8000e+00, 8.2000e+01, 0.0000e+00],
       [1.7881e+05, 7.8000e+00, 7.8000e+01, 2.5000e-01],
       [1.7881e+05, 7.8000e+00, 9.0000e+01, 0.0000e+00]])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [10]:
x_train

array([[1.8262e+05, 4.9000e+00, 7.1000e+01, 0.0000e+00],
       [1.7911e+05, 6.7000e+00, 3.9000e+01, 0.0000e+00],
       [1.7911e+05, 7.0000e+00, 2.9000e+01, 0.0000e+00],
       ...,
       [1.8262e+05, 5.0000e+00, 8.6000e+01, 0.0000e+00],
       [1.7911e+05, 7.0000e+00, 3.8000e+01, 0.0000e+00],
       [1.7881e+05, 7.6000e+00, 7.3000e+01, 3.0000e-02]])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
regressor = LinearRegression()

In [13]:
regressor.fit(x_train,y_train)

LinearRegression()

In [14]:
pred=regressor.predict(x_test)
pred

array([[11718.53419704],
       [12710.6559825 ],
       [12683.89968109],
       [11927.79957433],
       [11729.27984526],
       [11907.61646202],
       [12084.67483431],
       [12261.09285795],
       [11342.57587453],
       [12118.12021108],
       [11720.20646588],
       [12702.49799384],
       [12737.41228392],
       [12351.74343652],
       [11356.30093994],
       [12259.46277005],
       [12326.76722309],
       [12425.8282473 ],
       [12382.73835315],
       [11227.75706091],
       [12738.05919881],
       [12411.13384535],
       [12263.43394524],
       [12221.09930302],
       [11069.18455838],
       [ 9956.63198304],
       [ 9932.76652125],
       [10819.25749575],
       [12232.19031225],
       [11948.64499169],
       [11247.48757919],
       [11975.01219746],
       [11932.89163984],
       [11173.85293883],
       [11295.59427986],
       [12378.13040177],
       [12103.19685227],
       [12701.90554266],
       [12407.43329008],
       [ 9935.14068659],


In [15]:
print(y_test)

[[12082]
 [12398]
 [12951]
 [12149]
 [11967]
 [11648]
 [13088]
 [12230]
 [12320]
 [12949]
 [11881]
 [12028]
 [12448]
 [12483]
 [11493]
 [11910]
 [12388]
 [12539]
 [12258]
 [ 9660]
 [12444]
 [12635]
 [12230]
 [12456]
 [10502]
 [11032]
 [11011]
 [10488]
 [11946]
 [11788]
 [11045]
 [11782]
 [12154]
 [10404]
 [11244]
 [12703]
 [13105]
 [12765]
 [12764]
 [10956]
 [11792]
 [12375]
 [12300]
 [11665]
 [12391]
 [12795]
 [11924]
 [ 9613]
 [12290]
 [12051]
 [10664]
 [12627]
 [11134]
 [10942]
 [11781]
 [12069]
 [12565]
 [12771]
 [10488]
 [12212]
 [12285]
 [ 9927]
 [11933]
 [10767]
 [11634]
 [12358]
 [10218]
 [11334]
 [12902]
 [10761]
 [10437]
 [10287]
 [10675]
 [11856]
 [10432]
 [13154]
 [12531]
 [13156]
 [10424]
 [10295]
 [10653]
 [10543]
 [12082]
 [11882]
 [12702]
 [12513]
 [12152]
 [12224]
 [12461]
 [12268]
 [11080]
 [11676]
 [11606]
 [10887]
 [12545]
 [12785]
 [10423]
 [10816]
 [11958]
 [12179]
 [12355]
 [10938]
 [10722]
 [11698]
 [11854]
 [12585]
 [10778]
 [13098]
 [12765]
 [10227]
 [12144]
 

In [1]:
import matplotlib.pyplot